# Generated by Django 4.0.1 on 2022-01-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorite_likes_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='hotel',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='hotel',
            new_name='post',
        ),
    ]
